export const CONTEXT_WINDOW_TOKENS = 32_768;
export const COMPACTION_TRIGGER_TOKENS = CONTEXT_WINDOW_TOKENS * 0.8;
export const TARGET_CONTEXT_TOKENS = CONTEXT_WINDOW_TOKENS * 0.5;
export const SUMMARY_MAX_OUTPUT_TOKENS = TARGET_CONTEXT_TOKENS * 0.25;
